version: "3.8"

services:

  # -------------------------
  # Frontend Application #1
  # -------------------------
  app1:
    image: pranab7015/nginx_frontend:v1.0
    networks:
      - frontend_net

  # -------------------------
  # Frontend Application #2
  # -------------------------
  app2:
    image: pranab7015/nginx_frontend:v1.0
    networks:
      - frontend_net

  # -------------------------
  # Frontend Application #3
  # -------------------------
  app3:
    image: pranab7015/nginx_frontend:v1.0
    networks:
      - frontend_net

  # -------------------------
  # Nginx Load Balancer
  # -------------------------
  lb:
    image: pranab7015/nginx_lb:latest
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - frontend_net

# -------------------------
# Shared Network
# -------------------------
networks:
  frontend_net:
    driver: bridge
