server {
    listen 80;

    # Serve static frontend files
    location / {
        root       /usr/share/nginx/html;
        index      index.html;
        try_files  $uri $uri/ /index.html;
    }

    # /whoami — returns THIS container's hostname as JSON
    # This is the key endpoint for proving LB is working
    location /whoami {
        default_type  application/json;
        return 200    '{"hostname":"$hostname"}';
    }
}
